### ISSUE TITLE
datetime.datetime(2015, 2, 19, 17, 47, 43, 29120) is not JSON serializable

### ISSUE THREAD

**Issue by wailer** [ctrl-alt-d/django-aula#1]
Hola,  

Estic intentat instal·lar l'aplicació sota Ubuntu 14 LTS seguint la documentació i un cop faig el login, m'apareix aquest error:

TypeError at /

datetime.datetime(2015, 2, 19, 17, 47, 43, 29120) is not JSON serializable

Request Method: 	GET
Request URL: 	http://192.168.0.66:8000/
Django Version: 	1.6
Exception Type: 	TypeError
Exception Value: 	

datetime.datetime(2015, 2, 19, 17, 47, 43, 29120) is not JSON serializable

Exception Location: 	/usr/lib/python2.7/json/encoder.py in default, line 184
Python Executable: 	/usr/bin/python
Python Version: 	2.7.6
Python Path: 	

['/var/django-aula-master',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-x86_64-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/usr/lib/python2.7/lib-old',
 '/usr/lib/python2.7/lib-dynload',
 '/usr/local/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages']

Server time: 	dj., 19 Feb. 2015 17:47:43 +0100

Teniu idea del que pot ser ? Sota quin SO es recomanable instal·lar-ho ?

**Comment by ctrl-alt-d** [comment]
Per motius de seguretat djAu tanca la sessió després d'un temps d'innactivitat. El moment de la darrera connexió el guarda a la sessió com un datetime serialitzat.

El cas és que django va canviar el serialitzador per defecte a JSONSerializer i aquest nou serialitzador no sap serialitzar datetimes, llavors has de posar al fitxer de settings que faci servir [serializers.PickleSerializer](https://docs.djangoproject.com/en/1.6/topics/http/sessions/#django.contrib.sessions.serializers.PickleSerializer)

No sé pas perquè no està posat al fitxer general de settings:

https://github.com/ctrl-alt-d/django-aula/blob/master/aula/settings_dir/common.py

hi hauria de ser-hi.

Resum
======

Al teu fitxer de settings afegeix-hi:

    SESSION_SERIALIZER = 'django.contrib.sessions.serializers.PickleSerializer'
