### ISSUE TITLE
No apareixen totes les aules reservables quan es fa reserva a través de franja horària

### ISSUE THREAD

**Issue by juaky** [ctrl-alt-d/django-aula#10]
Si es fa una reserva d'aula a través de l'assistent de la tria d'aula, es pot reservar un aula :

![imagen](https://user-images.githubusercontent.com/4690871/46421823-4cc46900-c733-11e8-81bd-b22e4f2052f6.png)
<br>Si es fa la reserva a través de l'assistent de la tria de franja horària, l'aula reservable no apareix:

![imagen](https://user-images.githubusercontent.com/4690871/46421973-9e6cf380-c733-11e8-939c-50a405a01918.png)
<br><br>
El problema es reprodueix en pràcticament totes les aules.
Realitzant consultes des de la shell, es comprova que l'exclusió de les aules afectades es realitza a la línia  278 (i es fa efectiva a la línia 282) d'aquest fitxer:
https://github.com/ctrl-alt-d/django-aula/blob/master/aula/apps/aules/views.py

![imagen](https://user-images.githubusercontent.com/4690871/46422663-20115100-c735-11e8-8104-6359518d1303.png)

S'ha comprovat que les aules que sí apareixen com a reservables (no queden excloses) són aules amb només una reserva asociada en aquell dia. Tenint en compte aquesta casuística, s'ha intentat intentat reproduir l'error en un altre entorn sense èxit.

**Comment by ctrl-alt-d** [comment]
Veig que el problema està super acotat. Només cal posar valor a les variables i anar fent proves sobre la consulta.

En tot cas, el que podria estar passant, és que s'estigui fent mal barrejant consultes amb la interrelació N:M amb disponibilitat.

Jo el que faria seria partir la consula en consultes més petites:

```
    if hi_ha_classe_al_centre_aquella_hora:

        #reservables
        reservable_aquella_hora = ( Q(disponibilitat_horaria__isnull = True ) 
                                                    | Q(disponibilitat_horaria = franja )
        reservable_aquella_hora_ids = ( Aula
                                       .objects
                                       .filter( reservable_aquella_hora )
                                       .values_list('id', flat=True)
                                       .distinct() 
                                        )

	#reservades
        reservada = Q( reservaaula__dia_reserva = data )&Q(reservaaula__hora=franja)
        reservada_ids = ( Aula
                         .objects
                         .filter( reservada )
                         .values_list('id', flat=True) 
                         .distinct() 
                        )

        #lliures
        aules_lliures=( Aula
                       .objects
                       .exclude( reservable = False )
                       .filter( pk__in = reservable_aquella_hora_ids )
                       .exclude( pk__in = reservada_ids )
                       .distinct()
                    )
```

Si encara no funciona, sempre pots imprimir fàcilment les aules de cadascuna de les tres llistes i mirar quina és la que falla.

**Comment by juaky** [comment]
It Works!! Gràcies.
