### ISSUE TITLE
Proves pagament online

### ISSUE THREAD

**Issue by amorilla** [ctrl-alt-d/django-aula#107]
* [ ] Necessito ajuda técnica per tal de modificar o posar en marxa el programa.
* [x] Necessito ajuda funcional per entendre alguna pantalla.

Estic fent proves de pagament online utilitzant l'entorn de proves de redsys.
Faig servir les dades de proves, amb targetes de prova, segons [https://pagosonline.redsys.es/entornosPruebas.html](https://pagosonline.redsys.es/entornosPruebas.html)
Faci el que faci sempre torna a la pantalla de pagament del Djau i no informa del resultat del pagament. Fa el mateix amb targetes vàlides o no vàlides.
Es normal en l'entorn de proves de redsys ?
Salutacions i gràcies.

Aquestes són les variables CUSTOM:
CUSTOM_CODI_COMERÇ='999008881'
CUSTOM_KEY_COMERÇ='sq7HjrUOBfKmC576ILgskD5srU870gJ7'
CUSTOM_SORTIDES_PAGAMENT_ONLINE = True
CUSTOM_SORTIDES_PAGAMENT_CAIXER = False
CUSTOM_FORMULARI_SORTIDES_REDUIT = True
CUSTOM_REDSYS_ENTORN_REAL = False

**Comment by ctrl-alt-d** [comment]
En @juaky va fer el mòdul de pagament de sortides. Dius que necessites ajuda per fer pantalla nova, no et serveix el que va fer ell? No et funciona el que va fer en @juaky  com a exemple?

Salut!

**Comment by amorilla** [comment]
No es tracta d'això.
Estic fent servir l'entorn de proves de redsys i no surt la resposta del pagament.
Només vull saber si es normal qué en proves torni a la pantalla del Djau com si no s'hagués fet cap pagament o hauria de mostrar-se el resultat del pagament.

**Comment by ctrl-alt-d** [comment]
Invoco a @juaky

**Comment by juaky** [comment]
Hola,
efectivament torna a la pàgina del djAud però amb un "message" indicant si s'ha realitzat el pagament correctament.

**Comment by juaky** [comment]
No ho he fet mai amb les dades que proporciona l'entorn de proves de redsys directament. Sempre ho he fet amb la informació proporcionada per a nostra entitat (Banc Sabadell). Entenc que no ha de ser aquest el problema en ser tot Redsys.

Entenc que ho estàs provant en un entorn teu per fer proves. El tens configurat per rebre repostes des de fora?   
- ALLOWED_HOSTS = [ '*' ]
- Màquina/domini visible des de l'exterior.
- URL_DJANGO_AULA = r'http://domini_visible_des_de_lexterior'
- Redireccionament del port 80 d'entrada del router cap al port 8000 de la màquina on tens el djAu executant-se

Espero que puguis trobar el problema

**Comment by amorilla** [comment]
Hola,
  Efectivament, no havia tingut en compte la connexió externa. 
  He fet el que dius i ara funciona ok.
   Gràcies.
