### ISSUE TITLE
Presencia: ordenar diferent

### ISSUE THREAD

**Issue by ctrl-alt-d** [ctrl-alt-d/django-aula#11]
Hola,

tant quan arribes per primer cop a la pantalla (via get):

https://github.com/ctrl-alt-d/django-aula/blob/master/aula/apps/presencia/views.py#L373

Com quan fas submit i et mostra errors (via post):

https://github.com/ctrl-alt-d/django-aula/blob/master/aula/apps/presencia/views.py#L304

Veig que ordena per alumne. El que passa és que l'ordenació per alumne inclou el grup:

https://github.com/ctrl-alt-d/django-aula/blob/master/aula/apps/alumnes/abstract_models.py#L157

**Molt bona oportunitat per estrenar-te i enviar un Pull Request amb els canvis**

Canvis a fer:

0) Fas un fork del repo de github.

https://help.github.com/articles/fork-a-repo/

1) Creas un CUSTOM que digui per quin camp ordenem. Exemple:

```
CUSTOM_ORDER_PRESENCIA = ['alumne']
```

https://github.com/ctrl-alt-d/django-aula/blob/master/aula/settings.py#L3

2) Modificques la pantalla per tal que ordeni pel custom:

```
for control_a in ( impartir.controlassistencia_set
                           .order_by(**settings.CUSTOM_ORDER_PRESENCIA)):
```

3) Al teu settings local ordenes pel que vulguis:

```
CUSTOM_ORDER_PRESENCIA = ['alumne__cognoms','alumne__nom',]
```

4) Fas PullRequest dels canvis per a que tothom pugui disfrutar-ho:

https://help.github.com/articles/creating-a-pull-request-from-a-fork/

**Comment by jsubias6** [comment]
Moltes gràcies per l'ajuda, 
  Amb les indicacions he pogut crear el primer Fork i pujar-lo.
  He fet un canvi perquè donava error order_by(*settings.CUSTOM_ORDER_PRESENCIA)
  Això es pot quedar obert com a guia?

**Comment by ctrl-alt-d** [comment]
Les issues no s'esborren, es tanquen. La pots recuperar sempre que vulguis pel cercador.
Gràcies pel teu PR, vaig demanar un petit canvi, a veure si el podries fer.
Gràcies de nou per col·laborar. Tanco la issue.
