### ISSUE TITLE
Cal actualitzar documentació: carpeta d' imatges.

### ISSUE THREAD

**Issue by rafatecno1** [ctrl-alt-d/django-aula#118]
Les tutores m'avisen que no poden pujar les fotos dels alumnes i comprovo que rebo correu del sistema on se m'informa de que hi ha un problema. Desxifrant el correu, i amb ajuda dels companys del grup de Telegram, veig que el problema és amb el directori /dades/fitxers\_privats\_djAu/

La variable d'entorn PRIVATE\_STORAGE\_ROOT en settings.py guarda el nom d'una carpeta que no existeix a la meva instal·lació del djau.

**Comment by rafatecno1** [comment]
Per solucionar-ho he creat l'entrada següent en l'arxiu settings\_local.py

```
#Ruta on guardar dades privades, per exemple les fotos dels alumnes
PRIVATE_STORAGE_ROOT ='/opt/djau2020/aula/dades/fitxers_privats_djAu/'
```

A continuació he creat el directori i he donat permisos, de forma recursiva, al directori "dades" de la següent forma:

```
chgrp -R www-data dades
chmod -R 775 dades
```

**Comment by ctrl-alt-d** [comment]
Gràcies @rafatecno1 

Reobro issue: Cal actualitzar documentació. Caldria afegir les passes per crear i donar permisos a la carpeta aquí:

[https://github.com/ctrl-alt-d/django-aula/blob/master/docs/Wiki/instalacion-2/instalacion.md](https://github.com/ctrl-alt-d/django-aula/blob/master/docs/Wiki/instalacion-2/instalacion.md)

_Nota: ho marco com a Hacktoberfest per si algú s'anima a fer-ho dins la  [Hacktoberfest i guanyar una samarreta o plantar un arbre](https://hacktoberfest.digitalocean.com/)_
