### ISSUE TITLE
Quan es produeix una millora en el programari a meitat de curs, què s'ha de fer per actualitzar-ho tot?

### ISSUE THREAD

**Issue by rafatecno1** [ctrl-alt-d/django-aula#140]
> Atenció! No incloure dades sensibles en aquest formulari.

**Informa quin tipus d'ajuda necessites:**

*   [x] Necessito ajuda técnica per tal de modificar o posar en marxa el programa.
*   [ ] Necessito ajuda funcional per entendre alguna pantalla.

**Explica que tens fet fins ara:**  
Un centre té en marxa el servei Djaula i a meitat de curs apareix alguna actualització del programari que afegeix millores significatives pel centre. El dubte consisteix en saber quines son totes les passes que s'han de fer per tal d'actualitzar tant el programa com la base de dades existent i en producció a la nova versió.

**Comment by ctrl-alt-d** [comment]
### Intro

Si ets responable del djau en un centre, el millor que pots fer és:

* En primer lloc, activar el "Watch" del projecte per anar-te assabentant de tot el que passi:

![Activar watch shotscreen](https://user-images.githubusercontent.com/3105983/106436283-35692800-6474-11eb-87a6-c66e1ebe33d6.png)

* Les actualitzacions del programa es fan via PR, llavors, quan github et notifiqui que hi ha hagut merge d'una PR pots anar a mirar la PR a veure quines noves funcionalitats aporta, a la PR normalment s'explica si implica canvis a la BD o no.

### Actualitzar

La regla general seria:
   * Descarregar de nou djau a sobre del que tens ara. (Si ho tens descarregat amb un `git clone` molt possiblement amb un `git fetch` s'actualitzi)
   * Important no matxacar el teu `settings_local.py` on tens tots els teus paràmetres (El `git fetch` no el matxacarà perquè al repo no hi és aquest fitxer)
   * Executar les migracions. Per fer-ho, un cop activat el venv si en fas servir, executes `python manage.py migrate` (nota: pot ser que alguna versió no ho necessiti, però igualment es pot fer sempre)

### Notes

* Recorda fer còpies de seguretat de la base de dades i del programa periòdicament. Fes còpia abans d'actualitzar.
