### ISSUE TITLE
SAGA a Esfer@

### ISSUE THREAD

**Issue by ctrl-alt-d** [ctrl-alt-d/django-aula#15]
Cal fer el nou mòdul **ext_esfera**.

Hi ha diversos canvis a tenir en compte:

* Ara el fitxer és un XSLX ~(això no és problema perquè tenim la dependència `XlsxWriter` que ens ho soluciona)~ cal instal·lar openpyxl.
* Ara no s'importen tots els alumnes de cop. Per tant, el primer pas del procés d'importació serà mirar quins `Nivells` estem important i fer inserts i actualitzacions com sempre, però només baixes dels nivells que importem ( això tant a **ext_saga** com a **ext_esfera** )
* Hi ha camps disgregats que ens van bé, per exemple a **alumne** ja estem guardant a djau **nom** i **cognom** per separat tot i que al SAGA arriban junts. Però hi ha camps agregats que haurem de desagregar ( els contactes dels representants legals del menor )

Seria ideal disposar d'un XLSX amb dades FAKE però amb tots els casos contemplats.

### Informació proporcionada pel Cendrassos:

Per a l' ESO i el BTX ha deixat de funcionar SAGA, i hem passat a Esfer@. He estat provant quins llistat es poden extreure d'Esfer@ per poder importar alumnes a DJAU. En Quim S. ens passa aquest document amb la comparativa llistat SAGA-llistat Esfer@. Malauradament, les dades dels responsables legals no estan disgregades.

En aquests moments el DJAU treballa amb els fitxer CSV que tenen els següents camps i que s’extreu de SAGA::

```
        "00_IDENTIFICADOR DE L'ALUMNE/A",
	"01_NOM",
	"02_DATA NAIXEMENT",
	"03_RESPONSABLE 1",
	"04_TELÈFON RESP. 1",
	"05_MÒBIL RESP. 1",
	"06_ADREÇA ELECTR. RESP. 1",
	"07_RESPONSABLE 2",
	"08_TELÈFON RESP. 2",
	"09_MÒBIL RESP. 2",
	"10_ADREÇA ELECTR. RESP. 2",
	"11_ADREÇA",
	"12_LOCALITAT",
      	 "13_MUNICIPI",
	"14_CORREU ELECTRÒNIC",
	"15_ALTRES TELÈFONS",
	"16_CENTRE PROCEDÈNCIA",
	"17_GRUPSCLASSE"
```

En canvi d’Esfera@, la llista més semblant  en format XLSX (les treu en aquest format) que he pogut treure:

```
Identificador de l’alumne/a (25)
Primer Cognom (20)
Segon Cognom (20)
Nom (20)
Data naixement (20)
Tutor 1 - 1r cognom (20)
Tutor 1 - 2n cognom (20)
Tutor 1 - nom (20)
Contacte 1er tutor alumne - Valor (20)
Tutor 2 - 1r cognom (20)
Tutor 2 - 2n cognom (20)
Tutor 2 - nom (20)
Contacte 2on tutor alumne - Valor (20)
Tipus de via (15)
Nom via (20)
Número (15)
Bloc (15)
Escala (15)
Planta (15)
Porta (15)
Codi postal (15)
Localitat de residència (20)
Municipi de residència (20)
Correu electrònic (20)
Contacte altres alumne - Valor (20)
Grup Classe (20)
```

El problema que ens trobem és que des d’Esfer@ no podem obtenir els mateixos camps, i per tant dificulta la importació dels alumnes fins que no unifiquem a Esfer@ Cicles, Btx i ESO... (i en tenim per uns quants cursos)

LLISTA ESFER@ | SAGA | OBSERVACIONS
-- | -- | --
Identificador de l’alumne/a (25) | 00_IDENTIFICADOR DE L'ALUMNE/A | IGUAL
Primer Cognom (20) <td rowspan=3> 01_NOM | Caldrà unir els camps abans d'ajuntar els fitxers, o preparar el DJAU per camps separats (però després els problemes seran pel SAGA)
Segon Cognom (20)
Nom (20)
Data naixement (20) | 02_DATA NAIXEMENT | IGUAL
Tutor 1 - 1r cognom (20) <td rowspan=3> 03_RESPONSABLE 1 <td rowspan=3> Caldrà unir els camps abans d'ajuntar els fitxers, o preparar el DJAU per camps separats (però després els problemes seran pel SAGA)
Tutor 1 - 2n cognom (20)
Tutor 1 - nom (20)
Contacte 1er tutor alumne - Valor (20) <td rowspan=3> 04_TELÈFON RESP. 1 <td rowspan=3> Per esfer@ surten telèfons i mails al mateixa camp separats per espai-guionet-espa, i ordre diferent.  Serà complicat
05_MÒBIL RESP. 1
06_ADREÇA ELECTR. RESP. 1
Tutor 2 - 1r cognom (20) <td rowspan=3> 07_RESPONSABLE 2 <td rowspan=3> Caldrà unir els camps abans d'ajuntar els fitxers, o preparar el DJAU per camps separats (però després els problemes seran pel SAGA)
Tutor 2 - 2n cognom (20)
Tutor 2 - nom (20)
Contacte 2on tutor alumne - Valor (20) <td rowspan=3> 08_TELÈFON RESP. 2 <td rowspan=3> Per esfer@ surten telèfons i mails al mateixa camp separats per espai-guionet-espa, i ordre diferent.  Serà complicat
09_MÒBIL RESP. 2
10_ADREÇA ELECTR. RESP. 2
Tipus de via (15) <td rowspan=7> 11_ADREÇA <td rowspan=7> Caldrà unir els camps abans d'ajuntar els fitxers, o preparar el DJAU per camps separats (però després els problemes seran pel SAGA)
Nom via (20)
Número (15)
Bloc (15)
Escala (15)
Planta (15)
Porta (15)
Localitat de residència (20) | 12_LOCALITAT | IGUAL
Municipi de residència (20) | 13_MUNICIPI | IGUAL
Correu electrònic (20) | 14_CORREU ELECTRÒNIC | IGUAL
Contacte altres alumne - Valor (20) | 15_ALTRES TELÈFONS | IGUAL
  | 16_CENTRE PROCEDÈNCIA | Per obtenir-lo des d'Esfer@ s'ha de fer un altre llistat i després caldrà copiar/enganxar columna
Grup Classe (20) | 17_GRUPSCLASSE | IGUAL

### Exemple de com disgregar dades amb python:

```python
def dades_responsable ( dades ):
    splitted = dades.split(" - ")
    mails = [ dada for dada in splitted if "@" in dada ]
    fixes = [ dada for dada in splitted if dada.startswith("9") and dada not in mails ]
    mobils =[ dada for dada in splitted if dada not in mails+fixes ] 

    diccionari = { "mails": mails,
                   "fixes": fixes,
                   "mobils": mobils,
                 }
    return diccionari

print dades_responsable( "600016010 - 666780110 - pabrirodri1981@hotmail.com - joul@bicbaccroro.com" )
print dades_responsable( "123123123" )

```

[Try it online!](https://tio.run/##jVPLbtswELzzKwiebLQxyIIgqQAF9B9JEFCmZLOQRHVJIk2Lfru7pNL60Ryigz1YzczO7trLazqG@csp2mkZ@2dnk6VfKWOs0YJzw7Wmd1SJhgsluEBsRz9l6OzeBwjRtseQJuvH3T5MRAuhNXI5IQo/TSObhkQPHlArK7AFtYd/ktJGam4UWneQXR6tP4w5@ivnmoELIaQU6M0bJSRXgjgLPsddtB063woKpyQqGHtIjg6olcIgVkRpgxZGcHyfY3fM8D1nCO2rPYawy7HIpFaSN0ajjOMGeCUrVaSi4sV2OFRw4EVjxE2CbyGPbef3uKw94LbqwBi@7MiIGss0uGVpEA84wWSh8/rKhuDujeE4N3JwWUpzqQp2eQrQxQxgu3jT2MMQ2skfch7vfGch/3xrLXEKNMPzkreDQ3iJePCL8@/iMvq0YY8z255cP1BnXR@foY9LmHHTY083a41u7wnFpwpS79Cn1v86YBK2rYySrbR5KARLhwAr8PNZ7AfKWlZK9dVTFQ7@R/8BYantYrKQ4otPxw1r2Jba2a3kOaQiWEOsvlPoaqIP@F7JP62BniipNs7v8X8w468QM/6irHLY/cr9XCk3D6sGSKnf71PWcMWmgndIv2sJ@pRhvghBSBnkfNk6zvnO9VoL@Dn9f9PNpWxLyOn0Bw "Python 2 – Try It Online")

**Comment by juaky** [comment]
Informació a tenir en compte relacionada amb el fitxer .xlsx que exporta Esfera@:

- Segons l'exportació realitzada a l'institut Cendrassos, aquest fitxer té brossa fins la fila 6, columna 2. Aquest PR ho té en compte per tal de no importar aquestes cel·les.
- Segons l'exportació realitzada a l'institut Cendrassos, el fitxer afegeix una fila sense dades al final de la taula, Aquest PR ho té en compte per tal de no importar aquestes cel·les.
- El fitxer exportat de l'Esfera ha de tenir els següents camps:
	

> "Identificador de l’alumne/a",
> 	"Primer Cognom",
> 	"Segon Cognom",
> 	"Nom",
> 	"Data naixement",
> 	"Tutor 1 - 1r cognom ",
> 	"Tutor 1 - 2n cognom",
> 	"Tutor 1 - nom",
> 	"Contacte 1er tutor alumne - Valor",
> 	"Tutor 2 - 1r cognom ",
> 	"Tutor 2 - 2n cognom",
> 	"Tutor 2 - nom",
> 	"Contacte 2on tutor alumne - Valor",
>         "Tipus de via",
> 	"Nom via",
> 	"Número",
> 	"Bloc",
> 	"Escala",
>         "Planta",
>         "Porta",
>         "Codi postal",
>         "Localitat de residència",
>         "Municipi de residència",
>         "Correu electrònic",
>         "Contacte altres alumne - Valor",
>         "Grup Classe"
> 

Altres informacions a tenir en compte:

- S'utilitza la llibreria "openpyxl". Aquest PR l'afegeix com a requeriment per a futures instal·lacions. Al present curs 2018/2019 s'haurà d'afegir manualment des del virtual env:
    `venv) user@equip:/opt/django/djau2018/$ pip install openpyxl`
- S'afegeix un nou model per a Esfera. Per tant, al present curs 2018/2019 s'hauran de fer les migracions manualment des del virtual env:
    `(venv) user@equip:/opt/django/djau2018/$ python manage.py migrate`
