### ISSUE TITLE
Problema amb POLITICACOOKIES 

### ISSUE THREAD

**Issue by juaky** [ctrl-alt-d/django-aula#157]
Bones!
@amorilla tenim un problema amb els pagaments.
Sembla que ve pel paràmetre POLITICACOOKIES que s'ha afegit en [aquest commit ](https://github.com/ctrl-alt-d/django-aula/commit/37296ff97a1a8f4fb4a5d7e64bb8259565d1c008#diff-8ecb0835b749fb3afcff83c607d5040c4cebfd6ea2c4264571fb81538495b13e) al fitxer _aula/settings/dir_common_ referit al pagament de Quotes.
El nostre Institut no utilitza aquest mòdul de Quotes i el programa falla quan les famílies intentan fer el pagament d'una sortida ja que el fitxer POLITICACOOKIES no existeix.
Vegi que al commit també es va afegir el paràmetre POLITICA_RGPD al fitxer _aula/settings/dir_common_ i posiblement també donarà problemes si no existeix.
Suposo que si afegeixo aquests 2 fitxers a la nostra carpeta _customising/docs_ les famílies ja no tindran problemes. M'ho pots confirmar?   Sinò, caldria modificar aquest mòdul de forma que només utilitzi els 2 paràmetres si es fan servir Quotes.
Moltres gràcies!!!

**Comment by amorilla** [comment]
> Bones!
> @amorilla tenim un problema amb els pagaments.
> Sembla que ve pel paràmetre POLITICACOOKIES que s'ha afegit en [aquest commit ](https://github.com/ctrl-alt-d/django-aula/commit/37296ff97a1a8f4fb4a5d7e64bb8259565d1c008#diff-8ecb0835b749fb3afcff83c607d5040c4cebfd6ea2c4264571fb81538495b13e) al fitxer _aula/settings/dir_common_ referit al pagament de Quotes.
> El nostre Institut no utilitza aquest mòdul de Quotes i el programa falla quan les famílies intentan fer el pagament d'una sortida ja que el fitxer POLITICACOOKIES no existeix.
> Vegi que al commit també es va afegir el paràmetre POLITICA_RGPD al fitxer _aula/settings/dir_common_ i posiblement també donarà problemes si no existeix.
> Suposo que si afegeixo aquests 2 fitxers a la nostra carpeta _customising/docs_ les famílies ja no tindran problemes. M'ho pots confirmar? Sinò, caldria modificar aquest mòdul de forma que només utilitzi els 2 paràmetres si es fan servir Quotes.
> Moltres gràcies!!!

Hola,
El fitxer de POLITICA_RGPD no fa falta.
El fitxer de POLITICACOOKIES si és necessari. Posa un fitxer en blanc de moment.
Ho modificaré.
Salutacions.

**Comment by juaky** [comment]
Bones de nou @amorilla !!
Ara el problema està passant amb el paràmetre  POLITICA_RGPD. És el mateix problema que amb POLITICACOOKIES (no troba el fitxer "_aula/settings_dir/../../customising/docs/POLITICARGPD_"
El cas és que hi ha famílies que han pagat i no han tingut cap problema i amb algunes altres (poques) salta l'error. 
Per intentar esbrinar el perquè, m'he impersonat com a tutor d'una de les famílies que ha tingut el problema, he anat al portal de la família i he pogut arribar fins a la pasarel·la de pagament sense cap problema. No se m'ha reproduit el problema.
També he vist que ha aparegut l'error a una família que ni tan sols té activitats per pagar ¿¿??

**Comment by amorilla** [comment]
Hola,
Vaig fer uns canvis per solucionar-ho. Has actualitzat?
Aquests errors són després d'actualitzar?
Aquest fitxer POLITICA_RGPD ja existia abans d'afegir les quotes.
Només es fa servir si es consulten les condicions de pagament.
És obligatori que existeixi.
Miraré el codi.

Salutacions.

**Comment by juaky** [comment]
Hola @amorilla
Correcte, l'error segueix després d'actualitzar.
Però he aconseguit reproduir el problema.
Es tracta de famílies que en arribar a la pantalla de pagament fan click a l'enllaç per veure la "política de venda/devolucions"


![image](https://user-images.githubusercontent.com/4690871/133101398-cb5d4cf9-b353-42a7-9566-ae4fb0948968.png)

Això fa que vagi a https://github.com/ctrl-alt-d/django-aula/blob/402b622653ec270d4fcf3765ab41038cedc43286/aula/utils/views.py#L362
i entenc que a la línia 470 no troba el fitxer del RGPD i falla. https://github.com/ctrl-alt-d/django-aula/blob/402b622653ec270d4fcf3765ab41038cedc43286/aula/utils/views.py#L470

Per tirar endavant, afegiré un fitxer buit POLITICARGPD a la carpeta docs.

**Comment by amorilla** [comment]
Hola,

   Aquest fitxer és obligatori, ha d'existir. No el deixis en blanc, aquí et deixo un exemple:
`Institut XXXXXXXXXXXX

D'acord amb el que estableix el Reglament (UE) 2016/679, i l'article 11 de la llei Orgànica 3/2018 de 5 de desembre, de protecció de dades personals i garantia dels drets digitals, a continuació l'informem dels aspectes bàsics relatius al tractament de les seves dades personals. Pot ampliar aquestes informacions consultant les nostres condicions de matrícula.

El responsable del tractament de les seves dades personals és l'INSTITUT XXXXXXX, i seran tractades amb la finalitat de gestionar el pagament online de les quotes, sortides i esdeveniments en el nostre Centre educatiu. 
INSTITUT XXXXXXXX no comunicarà les seves dades a tercers, excepte de manera auxiliar o perquè així ho estableixi la Llei, com en el cas de la seva comunicació al Departament d'Educació de la Generalitat de Catalunya. El nostre Centre li ofereix la possibilitat de pagar online les quotes, sortides i esdeveniments, mitjançant la utilització d'una passarel·la de pagament. INSTITUT XXXXXXXX no té accés en cap moment a les seves dades bancàries o de les seves targetes (vegeu política de devolucions i condicions de matrícula). Pot exercir els seus drets d'accés, rectificació, cancel·lació i oposició de les seves dades personals, dirigint un escrit a l'Institut XXXXXXXXXX amb domicili social a ................................., adjuntant còpia del seu DNI.`

Salutacions.

**Comment by juaky** [comment]
Perfecte.
Gràcies

**Comment by amorilla** [comment]
Hola,
  He revisat aquesta issue i he vist que m'he confós amb algun fitxer. Per una banda he confós el fitxer INFORGPD amb POLITICA_RGPD i després em pensava que aquest últim era un altre fitxer anterior als últims afegits.
Una vegada he ordenat els meus pensaments he fet uns canvis, ara no és obligatori definir cap dels següents fitxers:
INFORGPD 
POLITICA_COOKIES
POLITICA_RGPD
De totes maneres és convenient tenir-los, permeten complir amb la llei de protecció de dades i, en el cas del nostre institut, també amb les condicions de contractació del tpv.
Funcionament:
a) Si no s'han definit al settings o s'han definit amb valor None, no surt cap informació.
b) Si s'han definit aleshores surt el contingut de cada fitxer al seu apartat.
c) S'han definit, però no existeixen. Aleshores surt, a l'apartat corresponent, un missatge d'avís:
                   "Fitxer fffffffffffffffffffffff no disponible"

Adjunto uns exemples d'aquests fitxers.
[INFORGPD.TXT](https://github.com/ctrl-alt-d/django-aula/files/7157760/INFORGPD.TXT)
[POLITICACOOKIES.TXT](https://github.com/ctrl-alt-d/django-aula/files/7157777/POLITICACOOKIES.TXT)
[POLITICARGPD.TXT](https://github.com/ctrl-alt-d/django-aula/files/7157758/POLITICARGPD.TXT)
Uns altres exemples de la resta de fitxer de condicions.
[DADESFISCALS.TXT](https://github.com/ctrl-alt-d/django-aula/files/7157757/DADESFISCALS.TXT)
[POLITICAVENDA.TXT](https://github.com/ctrl-alt-d/django-aula/files/7157759/POLITICAVENDA.TXT)
[MATRICULA.TXT](https://github.com/ctrl-alt-d/django-aula/files/7157756/MATRICULA.TXT)

Salutacions i lamento l'embolic.
