### ISSUE TITLE
Proposta de millora: Informació i/o simplificació dels tipus d'incidències

### ISSUE THREAD

**Issue by rafatecno1** [ctrl-alt-d/django-aula#163]
A l'hora de definir els tipus d'incidència que es volem adoptar sempre tinc una gran confusió per saber què implicació té internament (en el codi) una incidència o una altra.

Per exemple, en esborrar "incidència" per deixar només "lleu", com a parella de "greu" he observat que, com a professor, continua sortint "incidència" en el llistat de possibles incidències. Suposo que és degut a que els retards són incidències (en el codi) però realment crec que no està explicat enlloc.

Més dubtes que sorgeixen com admin, per exemple, 3 incidències són una Greu? 3 Lleus són una Greu?. la Greu no té res a veure amb allò anterior? La Greu seria equivalent a una expulsió de classe? El "Recull d'expulsió" compta sempre com una incidència? Si és així es pot configurar?

> 1.  Proposo una petita explicació en urldjaula/admin al costat de cada tipus d'incidència per saber amb quin objectiu hi són i si es un tipus es pot esborrar o no segons la implicació que pugui tenir.
> 2.  Proposo també un petit caixetí editable on l'admin pugui escriure un text d'informació al seu professorat que, segons les seves NOFC, informi de quines implicacions té cada tipus de sanció. D'aquesta manera eliminem una muntanya de dubtes i preguntes pels passadissos.
> 3.  Proposo poder triar l'ordre en el que apareixen les diferents incidències en la pàgina posaIncidenciaAula

**Comment by ctrl-alt-d** [comment]
Rafa,

El tema de les incidències "greus" va ser una ampliació que va fer un institut que distingien les incidències que calia notificar a l'equip directiu de les que no. Llavors, les greus, tenen a 'cert' enviar una notificació als membres de l'equip directiu. Al cendr***s no es fa servir crec, només tenen incidències i notificacions. Veig que per defecte també hi ha notificacions 'acadèmiques' (seria tipus 'no ha fet els deures' i coses semblants, entenc). Per defecte en venen 4, però ho pots deixar en 2 o en les que necessitis.

Amb relació al retard, per defecte, està configurat que generi una incidència, perquè al cendra***s es fa així. Però si al teu institut va diferent ho pots gestionar amb aquests paràmetres dels `settings_local.py`:

```python
CUSTOM_RETARD_PROVOCA_INCIDENCIA = True
CUSTOM_RETARD_TIPUS_INCIDENCIA = { 'tipus': u'Incidència', 'es_informativa': False }
CUSTOM_RETARD_FRASE = u'Ha arribat tard a classe.'
```

Deixo la incidència oberta per passar de 4 a 2 els tipus d'incidències per defecte.
