### ISSUE TITLE
Problema amb Pillow

### ISSUE THREAD

**Issue by juaky** [ctrl-alt-d/django-aula#184]
Des de la pantalla d'activitats, botó Accions:

![image](https://user-images.githubusercontent.com/4690871/155713519-c64deb31-6c87-4552-9ab8-2c0dfd90d3ab.png)

En seleccionar "imprimir fulls de pagament" o "imprimir fulls d'autorització i pagament" salta el següent error:

![image](https://user-images.githubusercontent.com/4690871/155713838-4375a209-368f-4924-83fe-7fd404c35d10.png)

El problema apareix a la línia 96 (codi_barres.save).

Des de la shell he vist que freetype2 no està actiu:
```
>>> from PIL import features
>>> features.check('freetype2')
False
```
Mirant solucions al problema he:
- instal·lat la llibreria libfreetype6-dev
- desinstal·lat i tornat a instal·lar Pillow a l'entorn virtual, 
sense èxit.

Versions:
- Python 3.6
- Pillow 8.4.0

Alguna idea de com solucionar-ho?
Gràcies

**Comment by amorilla** [comment]
Hola,

  Sembla que el problema és la compilació què es fa servir de pillow.
  Prova el següent:
   pip uninstall pillow
   pip cache purge   # Això elimina possibles paquets obsolets que pip guarda.
   pip install pillow==8.4

  En el meu cas fa instal·lació de Pillow-8.4.0-cp36-cp36m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl

  Amb Ubuntu 20.04, Python 3.6.15, Django 3.2.11 i Pillow 8.4 a mi em surt features.check('freetype2') --> True

   Salutacions.

**Comment by juaky** [comment]
Solucionat amb:
$ pip3 uninstall pillow
$ pip3 install --no-cache-dir Pillow

Moltes gràcies  @amorilla per les indicacions.
