### ISSUE TITLE
Com puc comprovar que els missatges d'incidències funcionen? Hi ha pares que no rebem missatges.

### ISSUE THREAD

**Issue by lenam462** [ctrl-alt-d/django-aula#19]
>Atenció! No incloure dades sensibles en aquest formulari.

**Informa quin tipus d'ajuda necessites:**

* [x] Necessito ajuda técnica per tal de modificar o posar en marxa el programa.
* [ ] Necessito ajuda funcional per entendre alguna pantalla.

**Explica que tens fet fins ara:**
Explica que tens desenvolupat i en quin punt estàs encallat. Quant més concret sigui el problema més fàcil serà que algú et pugui ajudar.

**Informació adicional**
Afegeix informació adicional que consideris rellevant. Captures de pantalla. Missatges d'error. Etc.

**Comment by ctrl-alt-d** [comment]
Algunes idees:

* Comprova que [et funciona el servei d'enviament de correus](https://docs.djangoproject.com/en/1.11/topics/email/#quick-example).
* Comprova que estàs executant l'script [notifica_families.sh](https://django-aula.gitbook.io/documentation/instalacion-2/instalacion#post-instalacion) Mira si el tens al cron
* Pots redirigir els errors de l'script anterior a un log i mirar que passa `./scripts/notifica_families.sh> /path_to_logs/notifica.log 2>&1`
* Entra al correu des d'on envies notificacions, safata de sortida, mira si allà hi ha correus enviats.
* Ves a [Accio](https://github.com/ctrl-alt-d/django-aula/blob/master/aula/apps/usuaris/abstract_usuaris.py) i comprova si estàs enviant notificacions:
* No deixes clar si cap pare rep missatges o són uns quants. Comprova les limitacions de número de correus del teu servei de missatgeria. 

```
from aula.apps.usuaris.models import Accio
accions = Accio.filter( tipus = 'NF' )
for accio in accions:
   print moment, text
```
>disclaimer: no ho he provat, ho he escrit tot de cap.
