### ISSUE TITLE
Problemes al Reprogramar

### ISSUE THREAD

**Issue by Jmoreno6** [ctrl-alt-d/django-aula#201]
>Atenció! No incloure dades sensibles en aquest formulari.

**Informa quin tipus d'ajuda necessites:**

* [x] Necessito ajuda técnica per tal de modificar o posar en marxa el programa.
* [ ] Necessito ajuda funcional per entendre alguna pantalla.

**Explica que tens fet fins ara:**
Explica que tens desenvolupat i en quin punt estàs encallat. Quant més concret sigui el problema més fàcil serà que algú et pugui ajudar.

Hola, estic intentat desplegar Django Aula al meu centre, i em trobo amb un problema.
He fet tots els passos del Document per al Desplegament fins Tareas Recomendables, ,
 al Crear Horari(Regenarar) no em crea cap horari

**Informació adicional**
Afegeix informació adicional que consideris rellevant. Captures de pantalla. Missatges d'error. Etc.

![Sin título](https://user-images.githubusercontent.com/113831693/191015290-0fa1a345-b4bb-4f8f-940b-e4c57deb8e88.png)

**Comment by ctrl-alt-d** [comment]
Comprova les dates d'inici i fi de curs:

https://github.com/ctrl-alt-d/django-aula/blob/master/docs/Wiki/manual-de-uso/carga-inicial-de-datos/creacion-de-niveles-cursos-y-grupos.md

**Comment by Jmoreno6** [comment]
Moltes gràcies!!
