### ISSUE TITLE
Potser caldria modificar el README per indicar instruccions per la Ubuntu 16.04

### ISSUE THREAD

**Issue by q2dg** [ctrl-alt-d/django-aula#3]
Segurament siguin les mateixes instruccions, però posant la darrera versió LTS li donaria un toc un xic més actual.

Gràcies

PD: D'altra banda, ja sé que potser és massa, però unes instruccions per Fedora (o algú de la família rpm: CentOS, Suse,...) no estaria malament tampoc

**Comment by ctrl-alt-d** [comment]
Hola,

encara queden 5 dies de 1.8 :)

En qualsevol cas aquest programari és codi obert, estàs convidat a fer la migració a la versió que necessitis i a documentar la instal·lació per a l'entorn que més t'agradi. Fes pull request i si tot és ok ho incorporo. Hi ha tot una llista de de coses a millorar, si vols contribuïr-hi ets benvingut.

Merci!!!

dani.
