### ISSUE TITLE
Eliminar l'opció expulsió per simplificar la gestió d'incidències (genera confusió)

### ISSUE THREAD

**Issue by lenam462** [ctrl-alt-d/django-aula#32]
>Atenció! No incloure dades sensibles en aquest formulari.

**Informa quin tipus d'ajuda necessites:**

* [x] Necessito ajuda técnica per tal de modificar o posar en marxa el programa.
* [ ] Necessito ajuda funcional per entendre alguna pantalla.

**Explica que tens fet fins ara:**
Explica que tens desenvolupat i en quin punt estàs encallat. Quant més concret sigui el problema més fàcil serà que algú et pugui ajudar.

**Informació adicional**
Afegeix informació adicional que consideris rellevant. Captures de pantalla. Missatges d'error. Etc.

**Comment by lenam462** [comment]
S'eliminarà l'opció d'expulsió. Per evitar confusions a l'hora de fer sancions de comportament a l'aula i fora de l'aula. Ja que la majoria de professorat entén l'expulsió com enviar l'alumne a casa, perd el dret a l'assistència al centre.  Quins paràmetres he de modificar?

**Comment by ctrl-alt-d** [comment]
### Opció 1:

1) Incidències i expulsions d'aula són conceptes 'hardcoded' al programa. Podries modificar el [menú](https://github.com/ctrl-alt-d/django-aula/blob/master/aula/utils/menu.py) i les plantilles per tal que no aparegui mai el concepte expulsió. 

2) Recorda que per tal que les incidències no generin expulsió cal sobreescriute el setting [CUSTOM_INCIDENCIES_PROVOQUEN_EXPULSIO](https://github.com/ctrl-alt-d/django-aula/blob/master/aula/settings.py#L9)  a false al local_settings.py

Inconvenient: el teu programa et quedarar molt tocat, dificultarà actualitzar versió.

### Opció 2:

Canviar el nom de les expulsions a "explusió de l'aula" a per tot on apareix expulsió. A la pantalla d'expulsió posar un redactat que es vegi que són expulsions de l'aula.

Pots preguntar si a tothom li està bé fer aquest canvi i fer-lo per tothom o bé fer un CUSTOM_DESCRIPCIO_EXPULSIO.

**Comment by lenam462** [comment]
La demanda des de direcció és fer desaparèixer l'opció per evitar problemes a l'hora de fer la gestió d'incidències perquè creant moltes incidències dobles i sobrecarrega la feina del tutor per eliminar les incidències duplicades.

**Comment by ctrl-alt-d** [comment]
Pel que comentes, sembla més un problema de que la UI no sigui prou entenedora. Amb una UI entenedora els professors haurien de saber que estan fent i també no entrar dades duplicades.

Crec que es tractaria de:

1) Investigar per què els professors creen incidències dobles. Què és que fan que entrin una segona incidència pel mateix.
2) Estudiar si modificant la interface d'usuari ( noms, descripcions, menú, informació, etc ) podem fer que això deixi de passar.

Tinc entès que s'està organitzant una trobada presencial per parlar de com es tracta la disciplina. Potser seria un bon lloc per on començar i aportar tot això. Sumar entre tots. De vegades petits canvis poden millorar moltíssim l'experiència d'usuari.

**Comment by quimsau** [comment]
has llegit aquest document sobre disciplina del DJAU, potser t'ajuda a veure a que són degudes les duplicitats d'incidències...
[Disciplina al DJAU.pdf](https://github.com/ctrl-alt-d/django-aula/files/2605633/Disciplina.al.DJAU.pdf)

**Comment by lenam462** [comment]
Bona nit

El problema es que tinc usuaris en majúscules. I són molts durs, pensa que
el dia de la formació inicial hi va haver que van bloquejar l'usuari , tot
i que els deia el teu usuari és X i la teva paraula de pas Y .  Fins i tot
va haver una que intentava logar l'usuari a un djau que no tocava ( crec
que el cendrassos). Imaginat.  Pero ara s'han liat amb les expulsions i el
recull d'expulsions. Es veu que el que l'expulsarà ja ha fet l'incidencia i
el que troba l'alumne al punt de guàrdia fa la recollida i per tant genera
un altre incident es el que he deduit que ha passat. Pero la veritat es
molt difícil de seguir el rastre per solucionar-ho.

Manel

El dc, 21 nov 2018 a les 21:11 quimsau <notifications@github.com> va
escriure:

**Comment by quimsau** [comment]
Hola,
Els mateixos professors s'haurien d'esborrar les incidències equivocades.

Jo penso que si elimineu les expulsions perdeu informació quan un professor
expulsi de classe no quedarà registrat en lloc.

Si confonen amb expulsió de centre, si que podeu afegir expulsió de classe.
Però en el nostre cas ningú ens ho havia demanar.

Quan s'expulsa a casa, només cap d'estudis pot fer-ho, ja s'indica els
dies, i per aixó al nostre centre no es crea confusió.

El que és important és que els professors s'han de fer responsables de les
seves accions (llistes, passar llista, observacions, incidències i
expulsions)... En el nostre institut, els professors nous s'adapten
ràpid... Ara també tenen l'ajuda dels que ja l'han usat un altre curs..

Si el centre abans no utilitzava cap aplicació, potser podríeu esperar a
enviar notificacions a les famílies fins que us hàgiu adaptat.

Per solucionar duplicitats hauràs de buscar expulsions, des d'usuari equip
directiu pots accedir a llistat d'alumnes expulsats i mirar un per un si té
duplicitats,... la feina dependrà si heu expulsat molts alumnes de classe...

No sé què dir-te més... Un dia ens ho podem mirar...

Quim





El dc. 21 de nov. de 2018 22.57, lenam462 <notifications@github.com> va
escriure:

**Comment by ctrl-alt-d** [comment]
Tanco la incidència perquè no hi ha més conversa. En tot cas es pot tornar a obrir si cal.
