### ISSUE TITLE
Bad Request (400) quan s'imprimeix informe Impersonalitzat

### ISSUE THREAD

**Issue by jsubias6** [ctrl-alt-d/django-aula#34]
>Atenció! No incloure dades sensibles en aquest formulari.

**Descriu el problema**
Quan fas una impersonació com un tutor, si accedeixes al menú de Impressió de faltes i incidències, al imprimir un informe, ens retorna un error web **Bad Request (400).** També es genera un report d'error 

**Passes per reproduir-ho**
Passes per reproduir aquest error:
1.Anar a  'Impersonació'
2. Impersonar-se com un tutor.
3. Anar a 'Tutoria'
4. Seleccionar 'Impressió de faltes i incidències'
5. Omplir les dades ('No imprimir recordatoris', 'Data des de' , 'Data fins a', 'Incloure XXX1A', 'Imprimir informe')
6. Apareix l'error: Bad Request (400)

**Comportament esperat*
Si es fa des de l'usuari retorna l'informe esperat.

**Captures de pantalla**

**Informació adicional**
The number of GET/POST parameters exceeded settings.DATA_UPLOAD_MAX_NUMBER_FIELDS.

Report at /tutoria/tutoriaInformeFaltesIncidencies/
The number of GET/POST parameters exceeded settings.DATA_UPLOAD_MAX_NUMBER_FIELDS.

Request Method: POST
Request URL: https://my.web/tutoria/tutoriaInformeFaltesIncidencies/
Django Version: 1.11.16
Python Executable: /usr/bin/python
Python Version: 2.7.15
(...)
Request information:
USER: super
GET: No GET data
POST: No POST data
FILES: No FILES data
(...)

**Error**

**Traces**

**Comment by ctrl-alt-d** [comment]
Algunes anotacions sobre aquesta issue:

Crec que les passes per a reproduir el problema no són correctes, *'Impressió de faltes i incidències'* és al menú gestió i no a tutoria. No cal impersonar-se per accedir a aquest llistat.

Aquest report existeix, però d'ençà que hi ha el "portal famílies", ha perdut el seu sentit. És un estalvi en paper important i una millora en immediatesa que les famílies consultin aquesta informació des del portal.

Aquest report, realment, envia moltíssims paràmetres, per  centres molt grossos pot ser que calgui ampliar el setting **DATA_UPLOAD_MAX_NUMBER_FIELDS** tal com diu l'error, heu provat d'incrementar aquest valor en un 30% o 50%, per exemple?

**Comment by jsubias6** [comment]
- A nosaltres no ens apareix a _'Gestió'_, ens apareix a _'Tutoria'_ i des dels usuaris de l'equip directiu o l'administrador no apareix l'opció de _'Tutoria'_. 

![imagen](https://user-images.githubusercontent.com/44383998/50057653-b3bbc080-016d-11e9-94c4-c33d2514b777.png)

- Teniu raó, però quan preparem expulsions o per pares que no tenen accés a internet ens va bé disposar d'aquest informe.

- I finalment, tens raó amb la solució, ha funcionat a 1500.

Moltes gràcies
