### ISSUE TITLE
Incidència assignada a tutor individualitzat per "retard d'entrada al centre"

### ISSUE THREAD

**Issue by juaky** [ctrl-alt-d/django-aula#37]
**Descriu el problema**
Si un alumne té un tutor individualitzat a més del seu tutor de grup, pot passar que se li assigni una incidència (per retard d'entrada al centre) al tutor individual i no al de grup. 

**Passes per reproduir-ho**
Passes per reproduir aquest error:
1. Entrar com a usuari conserge i posar un retard a un alumne que tingui tutor individualitzat i tutor de grup.
2. Se li  assignarà la incidència al primer tutor (individual o de grup) en ordre alfabètic per cognom.

**Comportament esperat*
S'espera la incidència se li assigni sempre al tutor del grup i no a l'individualitzat. Tots els alumnes tenen al menys un tutor de grup.

**Informació adicional**
Codi que prova l'error: https://github.com/ctrl-alt-d/django-aula/blob/master/aula/apps/incidencies/views.py#L419

**Possible solució**
- Incloure nova funció al model "Alumne": https://github.com/ctrl-alt-d/django-aula/blob/master/aula/apps/alumnes/abstract_models.py#L88
    ```
    def tutorsDelGrupDeLAlumne(self):
        return Professor.objects.filter(tutor__grup=self.grup).distinct()
- Substituir el codi que provoca l'error per :
    ```
    incidencia.professional = alumne.tutorsDelGrupDeLAlumne().first()

**Comment by ctrl-alt-d** [comment]
Això no és un bug. Això és un canvi de regla de negoci.

**Comment by juaky** [comment]
Solucionat amb el canvi de la regla de negoci
