### ISSUE TITLE
He pogut fer un merge a la branca Master.... i no hauria.

### ISSUE THREAD

**Issue by xeviterr** [ctrl-alt-d/django-aula#49]
No estic molt versat en el Git, però crec que he fet un merge a la Branca master d'una funcionalitat.
Si pot ser no em doneu aquest permís, la puc liar molt, no domino el Git com per fer aquestes coses. Abans crec que no ho podia fer.
En tot cas prometo no fer-ho més sense que reviseu el push request.
El que he afegit ara simplement era per actualitzar els tests a python3.

**Comment by ctrl-alt-d** [comment]
El PR és ok. Gràcies pel PR. 

No pateixis per liar-la, aquí tots l'hem liat vàries vegades, soms reincidents. Qui no la lia és perquè no toca prou.
