### ISSUE TITLE
Falla lectura de fitxers amb wsgi

### ISSUE THREAD

**Issue by amorilla** [ctrl-alt-d/django-aula#55]
Fent servir la versió de python3 amb apache i wsgi falla en lectura de fitxers.
Si s'executa amb runserver (sense wsgi) funciona ok.
He provat amb libapache2-mod-wsgi-py3.
He provat amb mod_wsgi des de python amb pip install mod_wsgi.
Amb les dues opcions s'obté el mateix comportament.

Per exemple falla a:
   Ajuda i Avisos / About
   Al llegir les cartes generades a Tutoria / Cartes

El problema és la lectura de fitxers:
aula/utils/view.py:
  Aquest codi falla:
def about(request):
  .....
    licenseFile = open (settings.LICENSE_FILE, "r")
    tip=licenseFile.read()    Aquesta és la línia que falla
    
  Copiant el fitxer LICENSE a carpeta static, amb aquest codi mostra el fitxer:
    import urllib.request as geturl
    f=geturl.urlopen("http://djau3.local/static/LICENSE")
    tip=f.read()

aula/apps/tutoria/report_carta_absentisme.py:
falla a         contingut = docFile.read()

No sé si estic fent res malament o no queda més remei que fer un canvi en la manera de llegir fitxers.

**Comment by ctrl-alt-d** [comment]
### Informació addicional:

Després de la migració de Python2 amb Python3 hi ha errors obrint fitxers de disc. Exemples dels errors:

**Cas 1**: Error en llegir fitxer de text ( llicència ):

```
File "/opt/djau2019/aula/utils/views.py", line 138, in about
tip=licenseFile.read()
File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 4: ordinal not in range(128)
```

**Cas 2: Generant els reports odt (cartes, expulsions, ....):

```
Als Gremlin no els ha agradat aquest fitxer! 'ascii' codec can't encode character '\xe8' in position 48: ordinal not in range(128)
```

### Relacionat:

Adjunto post d'stackoverflow amb Q/A relativa a aquest tipus d'incidència:

* [Switching to Python 3 causing UnicodeDecodeError](https://stackoverflow.com/questions/23917729/switching-to-python-3-causing-unicodedecodeerror)

Nota: El **cas 1** i el **cas 2** podria ser que s'haguessin de solucionar de maneres diferents.

**Comment by amorilla** [comment]
Hola,
  Crec que ja tinc el remei.
  Segons [https://modwsgi.readthedocs.io/en/develop/configuration-directives/WSGIDaemonProcess.html](https://modwsgi.readthedocs.io/en/develop/configuration-directives/WSGIDaemonProcess.html)

Al fitxer del virtualhos d'apache s'ha d'indicar el locale.

WSGIDaemonProcess djau python-home=/opt/djau2019/venv  python-path=/opt/djau2019 **locale="ca_ES.utf8"**

Ara sembla que tot va ok.

**Comment by ctrl-alt-d** [comment]
>

Genial! Meravellós si fas PR per actualitzar el [Document d'instal·lació](https://github.com/ctrl-alt-d/django-aula/blob/master/docs/Wiki/instalacion-2/instalacion.md) amb:

* Afegir la `WSGIDaemonProcess` al fitxer de l'apache.
* Afegir els [locales a l'ubuntu](https://askubuntu.com/a/76106/94244)

*Nota: no ho he provat, si algú més confirma que això soluciona, tanquem la issue amb el PR.*

Merci @amorilla !
