### ISSUE TITLE
Afegir franjes horaries a la pantalla de presencia aula

### ISSUE THREAD

**Issue by lenamlenam** [ctrl-alt-d/django-aula#61]
>;* [x] Necessito ajuda tècnica per tal de modificar o posar en marxa el programa.
* [ ] Necessito ajuda funcional per entendre alguna pantalla.

La pantalla de presència (on surt el quadre horari del professor) conté un nombre limitat de files (franges horàries). El meu problema és que jo actualment tinc 23 franges horàries i el cas que he capturat la imatge no surten totes les hores del seu horari a pantalla .

Adjunto la informació del fitxer d'horaris (podreu observar que les hores 16, 18 i 21 del dimecres ) no apareixen a la pantalla del djau i el fitxer si que hi són.

Com puc solucionar aquest problema?
![camphoto_1804928587](https://user-images.githubusercontent.com/50656481/64804366-fbea0100-d58e-11e9-8f92-c3dbb9feda8a.jpg)
![camphoto_684387517](https://user-images.githubusercontent.com/50656481/64804367-fbea0100-d58e-11e9-9c45-6594fe8160cb.jpg)

**Comment by lenamlenam** [comment]
Missatge de dani herrera <notifications@github.com> del dia dj., 12 de set.
2019 a les 22:16:

**Comment by ctrl-alt-d** [comment]
Was a user typo.
