### ISSUE TITLE
Error al fer les altes al dJau

### ISSUE THREAD

**Issue by jaumeteixidor** [ctrl-alt-d/django-aula#64]
Em dona error al carregar fitxer de alumnes de saga al djau.
L'error que em dona és el següent

Request Method: | POST
-- | --
https://ca.iesnx.cat/extSaga/sincronitzaSaga/
2.2.3
StopIteration
/opt/djau2019/aula/apps/extSaga/sincronitzaSaga.py in comprovar_grups, line 354
/opt/djau2019/venv/bin/python
3.6.8
['/opt/djau2019',  '/usr/lib/python36.zip',  '/usr/lib/python3.6',  '/usr/lib/python3.6/lib-dynload',  '/opt/djau2019/venv/lib/python3.6/site-packages']
dv., 13 Set. 2019 10:19:46 +0200

**Comment by ctrl-alt-d** [comment]
[Línia 354](https://github.com/ctrl-alt-d/django-aula/blob/master/aula/apps/extSaga/sincronitzaSaga.py#L354):

```
    grup_field = next( x for x in reader.fieldnames if x.endswith("_GRUPSCLASSE") )
```

Pots comprovar que quan has exportat el fitxer saga has inclós el camp `_GRUPSCLASSE` ?

Aquí trobaràs com exportar:

[https://github.com/ctrl-alt-d/django-aula/blob/master/docs/manuals/Tutorial%20ALUMNES%20SAGA-ESFER%40%20a%20DJAU.pdf](https://github.com/ctrl-alt-d/django-aula/blob/master/docs/manuals/Tutorial%20ALUMNES%20SAGA-ESFER%40%20a%20DJAU.pdf)

**Comment by jaumeteixidor** [comment]
Ok, sembla que era això... He fet exportació (que he hagut de tocar una mica) i ara em dona error amb el format de data. Quin ha de ser? jo tinc dd/mm/aa

**Comment by juaky** [comment]
Hola Jaume
Si no recordo malament nosaltres vam tenir el mateix problema
Es va tocar el codi i es va actualitzar aquests dies. 
Potser això? Has fet un pull de la darrera versió?

**Comment by jaumeteixidor** [comment]
Com es fa? modifica la resa de coses ja fetes?
gràcies

**Comment by juaky** [comment]
Quan vas clonarr el djAu es va crear un Git local al teu servidor. Desde aquesta carpeta has de fer:
git pull
Això actualitzarà el codi del djAu però no modificarà res de la base de dades (tot el que hagis fet abans continuarà allà)
Aquí tens una petita guía de git si vols saber més:
https://rogerdudler.github.io/git-guide/index.es.html

**Comment by ctrl-alt-d** [comment]
Recorda, després d'actualitzar, fer les migracions:

```
python3 manage.py migrate
```

Fes còpies de seguretat abans.

D'altra banda, veig que la darrera actualització del fitxer on es produeix l'error és de fa 5 mesos.

**Comment by jsubias6** [comment]
No sé si és això però dóna error si la data no és correcte o no existeix. mira-ho.

**Comment by ctrl-alt-d** [comment]
El format de data ha de ser `dd/mm/aaaa`, aquí tens un exemple:

https://github.com/ctrl-alt-d/django-aula/blob/master/demo/tmp/exportSaga.txt

Pot ser que hi hagi alguna data malament?

OffTopic: @juaky, aquest procés no està gaire 'blindat' perquè en principi estava molt controlat qui el feia i quan, però haurem de 'blindar-lo'. Per ara se m'acud: que comprovi els camps, que revisi les dates i la resta de camps que poden fer que el procés peti.

**Comment by jaumeteixidor** [comment]
Ok
He fet el pull i el migrate.
Ara em dona error en el fitxer. Diu que falten camps...
Per a fer proves he generat el cvs amb aquest contingut


#;"00_IDENTIFICADOR";"01_NOM";"02_DATA NAIXEMENT";"03_RESPONSABLE 1";"04_TELÈFON RESP. 1";"05_MÒBIL RESP. 1";"06_ADREÇA ELECTR. RESP. 1";"07_RESPONSABLE 2";"08_TELÈFON RESP. 2";"09_MÒBIL RESP. 2";"10_ADREÇA ELECTR. RESP. 2";"11_ADREÇA";"12_LOCALITAT";"13_Municipi";"14_CORREU ELECTRÒNIC";"15_ALTRES TELÈFONS";"16_CENTRE PROCEDÈNCIA";"17_GRUPSCLASSE"
1;"32772354597";"garcia , manel";"26/05/94";" , ";"No";"No";"No";" , ";"No";"No";"No";"CR Torres i Bages 19 5è 3era";"Salt";"Salt";"No";"No";"-";"MCT"
2;"32866292109";"chichi Creus, Joan";"15/04/79";" , ";"No";"No";"No";" , ";"No";"No";"No";"TR Mossen Plantes 3";"Bordils";"Bordils";"No";"No";"-";"1SDAS"
3;"30081569540";"prades Fradera, Jordi";"06/04/97";"ramon Gomez, Joan";"No";"No";"No";"perez Roura, Lidia";"No";"No";"No";"CR Ur els Pinars C/d'Artà 9  Bústia 102";"Lloret de Mar";"Lloret de Mar";"No";"No";"-";"2SDAS"

**Comment by ctrl-alt-d** [comment]
Com et comentava, a l'adreça:

https://github.com/ctrl-alt-d/django-aula/blob/master/demo/tmp/exportSaga.txt

tens un fitxer d'exemple. Jo els he comparat i he vist dues diferències:

1.- El teu fitxer fa servir `;` com a delimitador, però això no hauria d'afectar.
2.- Al teu fitxer, el camp `IDENTIFICADOR DE L'ALUMNE/A` es diu només `IDENTIFICADOR`. Això si que afecta, perquè [si mires el codi](https://github.com/ctrl-alt-d/django-aula/blob/master/aula/apps/extSaga/sincronitzaSaga.py#L73), veuràs que el djau busca per `IDENTIFICADOR DE L'ALUMNE/A`.

Llavors, mira de canviar aquest nom de columna. @juaky , saps si ha canviat aquest nom de columna i cal canviar-ho al djau?

**Comment by juaky** [comment]
Nosaltres hem fet la càrrega sense haver de modificar la capçelera del fitxer. 
A SAGA, l'export posa 00_IDENTIFICADOR DE L'ALUMNE/A
El vau modificar? Ho heu solucionat?

**Comment by ctrl-alt-d** [comment]
No hi ha resposta de @jaumeteixidor , tanco la issue.
