### ISSUE TITLE
Com es fa per modificar numero de faltes que creen una incidència?

### ISSUE THREAD

**Issue by jaumeteixidor** [ctrl-alt-d/django-aula#77]
Volia saber on és el paràmetre que diu quantes faltes es necessita per a generar una incidència.
Volem canviar el que ve per defecte (3) a 4.

Gràcies

**Comment by juaky** [comment]
Hola Jaume,
Et contesto pensant que el vostre centre i el nostre utilitza diferents definicions per a 'Falta'. 
Al nostre centre es considera 'Falta' a 'No assistir a classe' i entenc que al vostre centre es considera com a 'Falta Lleu'. Això que al nostre centre diem 'Incidència'

- Si és així,  veig que no està parametritzat i potser seria convenient fer-ho, ja que cada centre tindrà els seus criteris.:

https://github.com/ctrl-alt-d/django-aula/blob/a7fc52a068a50aeac1f31ee53ca0baad7bc6434d/aula/apps/incidencies/business_rules/incidencia.py#L139

- Si no és així. Suposo que et refereixes als retards. Aquests sí que poden o no generar el que nosaltres diem 'Incidències', i està parametritzat 
https://github.com/ctrl-alt-d/django-aula/blob/38782e7b9e1f49e7c4fa4bf32de60d6f8cafa96b/aula/settings.py#L4

**Comment by jaumeteixidor** [comment]
Si. És això. Hi ha la possibilitat de diferenciar entre els diferents tipus de incidència? és a dir, si és lleu o greu

**Comment by juaky** [comment]
Hola Jaume,

1. Respece al primer punt: _'Hi ha la possibilitat de diferenciar entre els diferents tipus de incidència? és a dir, si és lleu o greu'._

A què et refereixes en diferenciar-les.
Al nostre centre, les 'Incidències' (crec que per vosaltres són 'Faltes') que s'han creat al començament de curs són aquestes:

![imagen](https://user-images.githubusercontent.com/4690871/67011247-832b1700-f0ef-11e9-8063-079be1d3c2ae.png)

La primera d'elles és la que es té en compte per generar 'Expulsió' (quan arriba a 3) ja que no té la casella d'observació marcada:
![imagen](https://user-images.githubusercontent.com/4690871/67011375-c08fa480-f0ef-11e9-8b22-43772181b934.png)

En canvi, la segona es considera una observació i per això té la casella marcada. Això fa que no computi per generar expulsió :
![imagen](https://user-images.githubusercontent.com/4690871/67011422-dd2bdc80-f0ef-11e9-83ae-58f13f996c01.png)

Per vosaltres seria 

- una 'Falta Lleu' el que per nosaltres és una 'Observació' 
- una 'Falta Greu' el que per nosaltres és una 'Incidència'

A nosaltres ja ens queden força diferenciades així.

2.  Respecte al segon punt: _'I si volem canviar el nombre de retards que provoca la incidència? on puc modificar el número?'_

Si els Retards provoquen Incidència (_CUSTOM_RETARD_PROVOCA_INCIDENCIA = True_ ), cada 'Retard' provoca una 'Incidència'. 
Estem en el mateix cas que abans, són les Incidències les que, quan arriben a 3, generen una Expulsió. I per modificar això s'haurà de tocar el codi ja que no està parametritzat.

**Comment by jaumeteixidor** [comment]
No. Nosaltres tenim 2 tipus de incidències (lleu i greu) i una de observacions. El que preguntava és com es poden diferenciar els 2 tipus de incidències. Les observacions les fan servir per altres coses.
![imatge](https://user-images.githubusercontent.com/44392075/67142919-551c1300-f266-11e9-8575-4fbde95258a3.png)

![imatge](https://user-images.githubusercontent.com/44392075/67142935-8563b180-f266-11e9-9202-b522fbd01954.png)
![imatge](https://user-images.githubusercontent.com/44392075/67142943-901e4680-f266-11e9-8a5c-5c09d31d7199.png)

No sé si es pot...

**Comment by juaky** [comment]
Hola Jaume,
tal i com està programat ara mateix, no es pot
A veure si algú s'anima a fer-ho possible :wink:

**Comment by ctrl-alt-d** [comment]
>I el que vol equip directiu és que es reporti a la 4a lleu.

I les greus?

**Comment by ctrl-alt-d** [comment]
Tanco aquesta issue, no s'entén gaire. La pregunta és:

>Volia saber on és el paràmetre que diu quantes **faltes** es necessita per a generar una incidència.

Però no queda clar a què es refereix quan parla de **falta**:

* _falta = falta d'assistència_ ? Les faltes d'assistència no provoquen incidències.
* _falta = incidència_ ? Si una falta és una incidència llavors com pot provocar una incidència una altra incidència.

En un comentari es llegeix:

>Nosaltres tenim 2 tipus de incidències (lleu i greu) 
>...
>I el que vol equip directiu és que es reporti a la 4a lleu.

Que es reporti el què i a qui? Què passa amb les greus, no es reporten? 

Sisplau, torneu a obrir issue però definint el vostre escenari, definint els termes que feu servir (falta, incidència, reportar, crear incidència, ... ) i posant les captures de pantalles que calgui perquè es pugui entendre el que demaneu.

Està clar que a cada centre es fa servir un vocabulari diferent i fins i tot, de vegades, la mateixa paraula significa coses diferents en un centre o un altre. 

Comentar que la distinció entre falta greu i falta lleu va ser una extensió al djau que va aportar l'Ins de Vidreres al seu dia (igual que els diferents tipus de sancions: expulsió del centre, treballs a la comunitat, ... )
