### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by jaumeteixidor** [ctrl-alt-d/django-aula#87]
>Atenció! No incloure dades sensibles en aquest formulari.

Em dona problema al carregar fotos d'alumnes.
Sembla que es queixa de permisos a /alumnes.
Tota l'aplicació té com a propietari djau2019 i grup www-data.

**Passes per reproduir-ho**

Em passa al intentar carregar una foto d'un alumne. Qualsevol.
1 Vaig a portal
2 Li demano per carregar foto
3. La selecciono
4 Dono a enviar dades
5 veig error

En mode DEBUG el que dona és el que poso a continuació:

Request Method: | POST
-- | --
https://ca.iesnx.cat/open/configuraConnexio/17/
2.2.3
PermissionError
[Errno 13] S’ha denegat el permís: '/alumnes'
/usr/lib/python3.6/os.py in makedirs, line 220
/opt/djau2019/venv/bin/python
3.6.8
['/opt/djau2019',  '/usr/lib/python36.zip',  '/usr/lib/python3.6',  '/usr/lib/python3.6/lib-dynload',  '/opt/djau2019/venv/lib/python3.6/site-packages']
dc., 6 Nov. 2019 23:54:13 +0100

Environment:

Request Method: POST
Request URL: https://ca.iesnx.cat/open/configuraConnexio/17/

Django Version: 2.2.3
Python Version: 3.6.8
Installed Applications:
['customising',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.sites',
 'django_extensions',
 'django_tables2',
 'django.contrib.humanize',
 'aula.apps.missatgeria',
 'aula.apps.alumnes',
 'aula.apps.assignatures',
 'aula.apps.horaris',
 'aula.apps.presencia',
 'aula.apps.incidencies',
 'aula.apps.tutoria',
 'aula.apps.extKronowin',
 'aula.apps.extSaga',
 'aula.apps.extEsfera',
 'aula.apps.avaluacioQualitativa',
 'aula.apps.todo',
 'aula.apps.usuaris',
 'aula.apps.relacioFamilies',
 'aula.apps.sortides',
 'aula.apps.baixes',
 'aula.apps.BI',
 'aula.apps.aules',
 'aula.utils',
 'aula.apps.presenciaSetmanal',
 'aula.apps.extUntis',
 'private_storage']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'aula.utils.middleware.MultipleProxyMiddleware',
 'aula.utils.middleware.NoCacheMiddleware',
 'aula.utils.middleware.timeOutMiddleware',
 'aula.utils.middleware.IncludeLoginInErrors']

Traceback:

File "/opt/djau2019/venv/lib/python3.6/site-packages/django/core/handlers/exception.py" in inner
  34.             response = get_response(request)

File "/opt/djau2019/venv/lib/python3.6/site-packages/django/core/handlers/base.py" in _get_response
  115.                 response = self.process_exception_by_middleware(e, request)

File "/opt/djau2019/venv/lib/python3.6/site-packages/django/core/handlers/base.py" in _get_response
  113.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/opt/djau2019/venv/lib/python3.6/site-packages/django/contrib/auth/decorators.py" in _wrapped_view
  21.                 return view_func(request, *args, **kwargs)

File "/opt/djau2019/aula/utils/decorators.py" in inner_decorator
  17.                         return func(request, *args, **kwargs)

File "/opt/djau2019/aula/apps/relacioFamilies/views.py" in configuraConnexio
  204.             form.save()

File "/opt/djau2019/aula/apps/relacioFamilies/forms.py" in save
  42.         super(AlumneModelForm, self).save()

File "/opt/djau2019/venv/lib/python3.6/site-packages/django/forms/models.py" in save
  458.             self.instance.save()

File "/opt/djau2019/venv/lib/python3.6/site-packages/django/db/models/base.py" in save
  741.                        force_update=force_update, update_fields=update_fields)

File "/opt/djau2019/venv/lib/python3.6/site-packages/django/db/models/base.py" in save_base
  779.                 force_update, using, update_fields,

File "/opt/djau2019/venv/lib/python3.6/site-packages/django/db/models/base.py" in _save_table
  848.                       for f in non_pks]

File "/opt/djau2019/venv/lib/python3.6/site-packages/django/db/models/base.py" in <listcomp>
  848.                       for f in non_pks]

File "/opt/djau2019/venv/lib/python3.6/site-packages/django/db/models/fields/files.py" in pre_save
  288.             file.save(file.name, file.file, save=False)

File "/opt/djau2019/venv/lib/python3.6/site-packages/django/db/models/fields/files.py" in save
  87.         self.name = self.storage.save(name, content, max_length=self.field.max_length)

File "/opt/djau2019/venv/lib/python3.6/site-packages/django/core/files/storage.py" in save
  52.         return self._save(name, content)

File "/opt/djau2019/venv/lib/python3.6/site-packages/django/core/files/storage.py" in _save
  242.                     os.makedirs(directory)

File "/usr/lib/python3.6/os.py" in makedirs
  210.             makedirs(head, mode, exist_ok)

File "/usr/lib/python3.6/os.py" in makedirs
  220.         mkdir(name, mode)

Exception Type: PermissionError at /open/configuraConnexio/17/
Exception Value: [Errno 13] S’ha denegat el permís: '/alumnes'

**Comment by juaky** [comment]
Bones Jaume, al fitxer de configuració 'settings.py' està la variable que indica la ruta on es guardaran les dades sensibles:
https://github.com/ctrl-alt-d/django-aula/blob/3428412783c981e01f6293ff1fb9e2415218e075/aula/settings.py#L85
Aquest directori ('dades') ha d'existir i a més ha de ser propietat de l'usuari 'www-data' que utilitza l'Apache. Crec que aquest és el problema que tens. Si és així, prova de donar-li permisos: 

`$ chown -R www-data:www-data /dades`

**Comment by ctrl-alt-d** [comment]
També afegir que el fitxer `settings.py` **no l'haurieu de tocar mai**, perquè es matxaca amb les actualitzacions, cal tenir el fitxer `settings_local.py` amb les parametritzacions locals. [Quoting docs:](https://github.com/ctrl-alt-d/django-aula/blob/master/docs/Wiki/instalacion-2/instalacion.md#configurando-aplicaci%C3%B3n)

>**Configurando Aplicación**
>
>Django Aula tiene 3 archivos principales de configuración
>
>* `settings.py` (Aquí se encuentra la parametrización Custom de la app, **no hay que tocar este fichero**, sobreescribir los settings que se desee en settings_local.py) más info.
>* `settings_local.py` (Aquí esta la configuración principal ).
>* `wsgi.py` (Es el script que se encargará de levantar la aplicación, Apache utilizará este archivo para servir la app a través de él).

**Comment by jaumeteixidor** [comment]
He creat la carpeta /opt/djau2019/aula/dades/fitxers_privats_djAu/ i a settings_local he posat
PRIVATE_STORAGE_ROOT ='/dades/fitxers_privats_djAu/' 
He donat permisos amb 
chown -R www-data:www-data /dades
djau2019@freser:/opt/djau2019/aula$ ls -l
total 64
drwxr-xr-x 23 djau2019 www-data 4096 de no  4 17:54 apps
drwxr-xr-x  2 djau2019 www-data 4096 d’oct 16 12:36 assets
drwxr-xr-x  3 djau2019 www-data 4096 de no 11 10:39 dades
drwxr-xr-x  4 djau2019 www-data 4096 de ju 22 23:14 django_select2
-rw-r--r--  1 djau2019 www-data  294 de se 15 19:49 __init__.py
drwxrwxr-x  2 djau2019 www-data 4096 de no 11 10:54 __pycache__
drwxr-xr-x  3 djau2019 www-data 4096 de no  4 17:54 settings_dir
-rw-r--r--  1 djau2019 www-data 2604 de no 11 10:51 settings_local.py
-rw-rw-r--  1 djau2019 www-data 1160 de no  4 17:54 settings_local.sample
-rw-rw-r--  1 djau2019 www-data 3930 de no 11 10:49 settings.py
drwxr-xr-x 12 djau2019 www-data 4096 de no  4 17:54 site-css
drwxrwxr-x 15 djau2019 www-data 4096 de ju 22 23:17 static
drwxr-xr-x  2 djau2019 www-data 4096 de no  4 17:54 templates
-rw-rw-r--  1 djau2019 www-data 3262 de no  4 17:54 urls.py
drwxr-xr-x  6 djau2019 www-data 4096 de no  4 17:54 utils
-rw-r--r--  1 djau2019 www-data  154 de no 11 10:54 wsgi.py

Però ara es queixa de que no té accés a /dades (abans es queixava de que no tenia accés a /alumnes)

Em deixo alguna cosa?

Environment:


Request Method: POST
Request URL: https://ca.iesnx.cat/open/configuraConnexio/17/

Django Version: 2.2.3
Python Version: 3.6.8
Installed Applications:
['customising',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.sites',
 'django_extensions',
 'django_tables2',
 'django.contrib.humanize',
 'aula.apps.missatgeria',
 'aula.apps.alumnes',
 'aula.apps.assignatures',
 'aula.apps.horaris',
 'aula.apps.presencia',
 'aula.apps.incidencies',
 'aula.apps.tutoria',
 'aula.apps.extKronowin',
 'aula.apps.extSaga',
 'aula.apps.extEsfera',
 'aula.apps.avaluacioQualitativa',
 'aula.apps.todo',
 'aula.apps.usuaris',
 'aula.apps.relacioFamilies',
 'aula.apps.sortides',
 'aula.apps.baixes',
 'aula.apps.BI',
 'aula.apps.aules',
 'aula.utils',
 'aula.apps.presenciaSetmanal',
 'aula.apps.extUntis',
 'private_storage']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'aula.utils.middleware.MultipleProxyMiddleware',
 'aula.utils.middleware.NoCacheMiddleware',
 'aula.utils.middleware.timeOutMiddleware',
 'aula.utils.middleware.IncludeLoginInErrors']



Traceback:

File "/opt/djau2019/venv/lib/python3.6/site-packages/django/core/handlers/exception.py" in inner
  34.             response = get_response(request)

File "/opt/djau2019/venv/lib/python3.6/site-packages/django/core/handlers/base.py" in _get_response
  115.                 response = self.process_exception_by_middleware(e, request)

File "/opt/djau2019/venv/lib/python3.6/site-packages/django/core/handlers/base.py" in _get_response
  113.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/opt/djau2019/venv/lib/python3.6/site-packages/django/contrib/auth/decorators.py" in _wrapped_view
  21.                 return view_func(request, *args, **kwargs)

File "/opt/djau2019/aula/utils/decorators.py" in inner_decorator
  17.                         return func(request, *args, **kwargs)

File "/opt/djau2019/aula/apps/relacioFamilies/views.py" in configuraConnexio
  204.             form.save()

File "/opt/djau2019/aula/apps/relacioFamilies/forms.py" in save
  42.         super(AlumneModelForm, self).save()

File "/opt/djau2019/venv/lib/python3.6/site-packages/django/forms/models.py" in save
  458.             self.instance.save()

File "/opt/djau2019/venv/lib/python3.6/site-packages/django/db/models/base.py" in save
  741.                        force_update=force_update, update_fields=update_fields)

File "/opt/djau2019/venv/lib/python3.6/site-packages/django/db/models/base.py" in save_base
  779.                 force_update, using, update_fields,

File "/opt/djau2019/venv/lib/python3.6/site-packages/django/db/models/base.py" in _save_table
  848.                       for f in non_pks]

File "/opt/djau2019/venv/lib/python3.6/site-packages/django/db/models/base.py" in <listcomp>
  848.                       for f in non_pks]

File "/opt/djau2019/venv/lib/python3.6/site-packages/django/db/models/fields/files.py" in pre_save
  288.             file.save(file.name, file.file, save=False)

File "/opt/djau2019/venv/lib/python3.6/site-packages/django/db/models/fields/files.py" in save
  87.         self.name = self.storage.save(name, content, max_length=self.field.max_length)

File "/opt/djau2019/venv/lib/python3.6/site-packages/django/core/files/storage.py" in save
  52.         return self._save(name, content)

File "/opt/djau2019/venv/lib/python3.6/site-packages/django/core/files/storage.py" in _save
  242.                     os.makedirs(directory)

File "/usr/lib/python3.6/os.py" in makedirs
  210.             makedirs(head, mode, exist_ok)

File "/usr/lib/python3.6/os.py" in makedirs
  210.             makedirs(head, mode, exist_ok)

File "/usr/lib/python3.6/os.py" in makedirs
  210.             makedirs(head, mode, exist_ok)

File "/usr/lib/python3.6/os.py" in makedirs
  220.         mkdir(name, mode)

Exception Type: PermissionError at /open/configuraConnexio/17/
Exception Value: [Errno 13] S’ha denegat el permís: '/dades'

Gràcies

**Comment by juaky** [comment]
La variable `PRIVATE_STORAGE_ROOT ='/dades/fitxers_privats_djAu/`' que tens a `settings_local.py`  indica una ruta absoluta, per tant has de crear el directori 'dades' a l'arrel

**Comment by jaumeteixidor** [comment]
....
Sense paraules.
Gràcies

**Comment by jaumeteixidor** [comment]
Perdoneu la ignorància, però he posat la adreça absoluta
/opt/djau2019/dades/fitxers_privats_djAu/
I em continua dient el mateix missatge. 
Exception Type: PermissionError at /open/configuraConnexio/17/
Exception Value: [Errno 13] S’ha denegat el permís: '/dades'

Per a més info, ho he posat a settings_local

Gràcies

Què he de fer, un Touch wsgy? o restart de apache?

**Comment by juaky** [comment]
Bones Jaume,
aquesta carpeta dades es propietat de 'www-data'?

**Comment by juaky** [comment]
Nosaltres tenim la carpeta `dades` a  l'arrel, ja que quan es va programar es va considerar que estaria millor tenir aquestes dades bén localitzades per fer còpies de seguretat. A més, les fotos dels alumnes es podran reutilitzar per posteriors cursos.

**Comment by jaumeteixidor** [comment]
Ok.
El problema era aquí.
Havia donat la carpeta dades a djau2019:www-data (és el propietari de totes les altres carpetes de l'aplicació), i veig que ha de ser de www-data:www.data.
Ara sembla que funciona.
Moltes gràcies

**Comment by juaky** [comment]
Perfecte, tanco l'issue.
