### ISSUE TITLE
Incidència a l'hora d'enviar notificacions diàries als pares

### ISSUE THREAD

**Issue by manellenam** [ctrl-alt-d/django-aula#88]
Els pares del alumnes no estan rebent el missatge diari amb les incidències.

Hi ha dos possibles casos:

Pares donats d'alta al sistema i han completat l'accés al portal, i no reben missatges.

Pares convidats que no completen l'accés al portal, (normalment els que tenen més incidències), no reben missatges.

Com ho puc solventar?

Hem fer la prova amb dos alumnes test (els fills del Cap d'estudi i la coordinadora pedagògica), han posat incidències i no han rebut missatge.

**Comment by ctrl-alt-d** [comment]
Hola,

### Resposta ràpida

Si els pares no reben correus cal fer dues comprovacions:

1.- Què tens el sistema de sendmail ben configurat.
2.- Què tens posat al cron que s'enviin els missatges.

Cal comprovar els dos punts. Si no és res d'això, cal procurar posar més info a la issue: configuració,  proves realitzades, descripció dels intents d'aïllar el problema i els resultats, contingut delss logs, etc.

Salut.

### Detalls sendmail:

Cal tenir el correu configurat, al fitxer `settings_local.py`:

```
#Configuracion del Correo Relay SMTP de la Aplicacion
EMAIL_HOST='smtp.gmail.com'
EMAIL_HOST_USER='juan@xtec.cat'
EMAIL_HOST_PASSWORD='xxxx xxxx xxxx xxxx'
DEFAULT_FROM_EMAIL = 'Institut Badia <no-reply@ibadia.cat>'
EMAIL_PORT=587
EMAIL_USE_TLS=True
SERVER_EMAIL='ibadia@xtec.cat'
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_SUBJECT_PREFIX = '[Comunicacio Institut Badia del Valles] '
```

Per comprovar que [es poden enviar correus](https://docs.djangoproject.com/en/2.2/topics/email/):

```
from django.core.mail import send_mail

send_mail(
    'Subject here',
    'Here is the message.',
    'from@example.com',
    ['to@example.com'],
    fail_silently=False,
)
```

### Detalls cron:

A l'apartat [post instal·lació](https://github.com/ctrl-alt-d/django-aula/blob/master/docs/Wiki/instalacion-2/instalacion.md#post-instalaci%C3%B3n) s'explica que cal configurar el cron. L'script `notifica_families.sh` és el responsable de la gestió de les notificacions.

```
42 8,9,10,11,12,13,14,15,16,17,18,19,20,21 * * 1,2,3,4,5 su - www-data -c "/opt/djau2019/scripts/notifica_families.sh" >> /opt/django/log/notifica_families_`/bin/date +\%Y_\%m_\%d`.log 2>&1
```

**Comment by ctrl-alt-d** [comment]
Tanco issue per inactivitat.
