### ISSUE TITLE
Estat de sincronització manual no bloqueja sincronització automàtica

### ISSUE THREAD

**Issue by quimsau** [ctrl-alt-d/django-aula#90]
### Des del menú Alumnes d'Administració es pot escollir tipus de sincronització:
![image](https://user-images.githubusercontent.com/45243673/68854793-1b132500-06dd-11ea-911c-c014d79a0451.png)

### ERROR: Quan s'escull ALUMNE DONAT D'ALTA MANUALMENT no s'hauria de SINCRONITZAR amb SAGA/ESFER@ i ho fa.

![image](https://user-images.githubusercontent.com/45243673/68854497-78f33d00-06dc-11ea-975c-23e819df281f.png)

**Comment by amorilla** [comment]
Actualment, per error, es modifica l'estat de sincronització i al final l'alumne acaba sincronitzat o de baixa.
Quin seria el comportament desitjat?:
a) Els alumnes manuals no sincronitzen mai encara que estiguin inclosos en el fitxer d'importació.
b) Els alumnes manuals han de conservar-se tal qual fins que són inclosos en el fitxer d'importació i deixen de ser manuals.

**Comment by ctrl-alt-d** [comment]
@amorilla , gràcies pel seguiment de la issue. Vaig a fer forward del teu missatge a en @quimsau . Jo no tinc resposta, sempre havia pensat que era millor evitar "alumnes entrats a mà":

* per mi si un alumne està matriculat, hauria de ser al Saga,
* si no hi és al saga, sembla una opció fàcil afegir-lo al CSV abans de ser sincronitzar

Realment cal entrar alumnes a mà des d'admin?

**Comment by quimsau** [comment]
A vegades tenim problemes per matricular alumnes, i ho fem manualment, però modificant el fitxer que obtenim de saga o esfera. Per exemple, hem tingut 2 alumnes pendents de matricula 15 dies. Això implica que cada vegada que actualitzem alumnes, els hem d'entrar abans al fitxer. De les dues opcions veig útil la b. Així una vegada carregats i seleccionat sincronització manual podriem actualitzar alumnes sense que causessin baixa fins a estar matriculats correctament a esfera o a saga

**Comment by quimsau** [comment]
hola Dani, entenc que s'ha arreglat aquest problema i que ara:
Els alumnes manuals han de conservar-se tal qual fins que són inclosos en
el fitxer d'importació i deixen de ser manuals.
https://github.com/ctrl-alt-d/django-aula/pull/126/files (m'ho he mirat...
però evidentment, no ho he entès)
- alumnes que no estan matriculats a ESFERA o SAGA, els insereixo als
fitxers, els carrego al DJAU i els passo a SINCRONITZACIÓ MANUAL.
- Si torno a sincronitzar alumnes, no cal que els torni posar a la fitxer
extret d'ESFERA o SAGA, quedaran amb al seu estat fins que estiguin ben
matriculats a EFERA o SAGA.

Vinga, ja tens el corral preparat? 🐏🐏

Ens veiem

Quim

Missatge de dani herrera <notifications@github.com> del dia ds., 24 d’oct.
2020 a les 18:51:

**Comment by ctrl-alt-d** [comment]
Hola @quimsau 

Jo he entès que l'aportació d'en @amorilla fa això que dius, però no ho he provat.

Potser en Toni ens ho pot confirmar.

**Comment by ctrl-alt-d** [comment]
Oh! @quimsau , a banda, li has de preguntar a en @juaky si ha actualitzat a la versió que incorpora això. Potser ell al seu entorn de dev et pot provar si fa el que demanes.

**Comment by amorilla** [comment]
Hola,
   Efectivament, aquest és el comportament després dels canvis.
     Salutacions.
