### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by jaumeteixidor** [ctrl-alt-d/django-aula#95]
>Atenció! No incloure dades sensibles en aquest formulari.

Apareixen franges horàries fantasma. És a dir, en horari del professor apareix en algunes "caselles" que no tenen correspondència amb la taula d'horaris(és a dir, des de la consola d'administrador).
Si es clica en aquestes "caselles" posa dades que no es corresponen amb les que es veuen en l'horari, i redirigeixen a una altra hora (normalment de la mateixa assignatura i professor, que si que existeix en una altra franja horària).
No sé com reproduir l'error, però us puc mostrar el que ens passa a nosaltres:

![imatge](https://user-images.githubusercontent.com/44392075/74585652-31cc5f00-4fdf-11ea-8cb7-e50d4336643d.png)

Podeu veure que el dimarts a primera hora hi ha 2 assignatures per el mateix professor. La primera és correcta, la segona no hi hauria de ser.
Si premem per a passar llista podeu veure que refereix a una entrada del dimarts, no del divendres:
![imatge](https://user-images.githubusercontent.com/44392075/74585669-7ce67200-4fdf-11ea-9bfa-8f2a37060210.png)
 I si mirem les entrades de diari veiem que la de dimarts no existeix:
![imatge](https://user-images.githubusercontent.com/44392075/74585688-bae39600-4fdf-11ea-965d-9cb14e7c48fb.png)
on podeu veure que el dimarts a 1a hora no hi ha la assignatura fantasma.
No hi ha cap traça problemàtica ni res semblant. No sé com buscar l'origen de l'error. Si m'orienteu puc intentar marcar una traça de l'error.
Gràcies

**Comment by ctrl-alt-d** [comment]
>Si es clica en aquestes "caselles" posa dades que no es corresponen amb les que es veuen en l'horari, i redirigeixen a una altra hora (normalment de la mateixa assignatura i professor, que si que existeix en una altra franja horària).

Jo crec que s'ha equivocat i ha pintat la casella dues vegades. Un cop allà on toca (el divendres) i un altre cop en un lloc erroni (el mimarts). Crec que és la mateixa pel número de impartició, el 76530.

Ara caldria veure com pot ser que això es pinti malament. Et demanaria que amb les dev tools comprovis que són caselles html diferents i que realment està dins del dimarts.

El codi que calcula el que s'ha de mostrar és aquest: https://github.com/ctrl-alt-d/django-aula/blob/master/aula/apps/presencia/views.py#L117 fa molt de temps que està fet i fins ara (crec) que ningú ha tingut aquest problema.

@juaky se t'acudeix que podria ser?

En tot cas, @jaumeteixidor, gràcies per reportar-ho i intentar aïllar la causa. A veure si entre tots veiem que està passant.

**Comment by jaumeteixidor** [comment]
No sé com ho he de fer amb les dev tools. De tota manera, he mirat unes setmanes enrere i veig això

![imatge](https://user-images.githubusercontent.com/44392075/74917050-3457fb80-53c7-11ea-8d79-ee80b35bf78d.png)

Per tant veig difícil que sigui la mateixa que la pinta dues vegades, ja que per una consta que s'ha passat llista i per l'altra no. Pot ser una resta que ha quedat a la BD al moure un horari? em sembla que a aquest professor se li va retocar els horaris des de la part d'administració. 
Si és així suposo que seria una entrada a la base de dades que ha quedat "orfe"

**Comment by jaumeteixidor** [comment]
Suposo que vols dir això...
![imatge](https://user-images.githubusercontent.com/44392075/74918558-87cb4900-53c9-11ea-80aa-8a8da9937d93.png)
![imatge](https://user-images.githubusercontent.com/44392075/74918571-8d289380-53c9-11ea-998b-99bc1a70bb83.png)

**Comment by ctrl-alt-d** [comment]
>em sembla que a aquest professor se li va retocar els horaris des de la part d'administració.

Uhmmmm, qui té un gran poder té una gran responsabilitat. Si es toquen coses a mà des d'administració, tens el poder de deixar-ho incoherent. És millor, sempre que es pugui, fer servir les pantalles de l'aplicatiu i els processos previstos per a això.

El procés d'[actualitzar horaris](https://github.com/ctrl-alt-d/django-aula/blob/master/aula/apps/extKronowin/sincronitzaKronowin.py), per exemple, es força 'sensible', perquè cal marcar horaris obsolets i gestionar un munt de detalls. Comprova que has marcat com a obsolet ( `es_actiu=False` ) aquest horari que no ha d'aparèixer. Recorda 'reprogramar' classes després de tocar horaris. D'altre banda, qué has tocat des d'admin? Els horaris o les imparticions? (són coses diferents, horari és la informació de quines classes hi ha cada dia de la setmana i les imparticions són les classes desplegades al calendari amb els seus alumnes )

**Comment by jaumeteixidor** [comment]
No hi ha cap entrada ni activa ni no activa a la franja horària marcada. Cada vegada que toco coses reprogramo. No sé com tocar les imparticions. El que he tocat és les entrades de horari que hi ha des de la consola d'administració. En alguns casos he canviat el professor (perquè estava de baixa) i en algun altre he tocat horaris (o he canviat grup o professor o horari...).

**Comment by ctrl-alt-d** [comment]
Tocar horaris des de la consola no està suportat, s'ha de fer des del procés d'actualitzar horaris. El procés de canviar horaris deixa obsolets horaris vells i crea els nous, i, a partir d'aquesta info pot gestionar les imparticions (esborrar les dels horaris que han quedat obsolets i crear les noves imparticions). Es tracta d'un "procés de negoci", no un simple "canvi a les dades de l'horari".

Admin és molt potent però permet deixar les coses inconsistents.

**Comment by ctrl-alt-d** [comment]
Tanco aquesta issue.
